all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    master:
      hosts:
        master001:
          ansible_host: 192.168.0.193
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3

    worker:
      hosts: {}
        # worker001:
        #   ansible_host:

    kubernetes:
      children:
        master: {}
        worker: {}
